### ISSUE TITLE
Requesting to release a new tag for Live activity support

### ISSUE THREAD

**Issue by hariom-palkar** [jchambers/pushy#1004]
Heyyy Jon,

Hope you are doing well. Our team has been following the release of the tag and are excited about the potential of using it to create payloads for live activity. We really appreciate the hard work you have put into maintaining and updating the library – it is truly an excellent resource.

We would be grateful if you could assist us with releasing the tag.

Thank you very much in advance for your assistance.

Best, 
Hariom

**Comment by jchambers** [comment]
Thank you for your enthusiasm. As I explained in https://github.com/jchambers/pushy/pull/990#issuecomment-1329968779, I will put out a new release as soon as I can. This has not changed. I understand that it's taking longer than originally estimated and that this is an important feature for many users and promise I will do this as soon as my schedule allows me to do so with quality.

**Comment by hariom-palkar** [comment]
Thank you so much for releasing the tag @jchambers appreciate the efforts as always! 🥇
