### ISSUE TITLE
upgrade the netty-transport from 4.0.37 to 4.1.37

### ISSUE THREAD

**Issue by lijhua** [jchambers/pushy#1011]
Class ApnsChannelFactory  Bootstrap's  resolver method does't exist in netty4.0.37

**Comment by jchambers** [comment]
I'm confused; Pushy depends on Netty 4.1.85. Why do you think we're using 4.0.37?

**Comment by lijhua** [comment]
sorry, What I want to express is that my system is already relying on the nety-handler-proxy version 4.0.37. When I use "push", I find that "nety" has a big conflict, and many methods are incompatible
