### ISSUE TITLE
push 0.15.1 io.netty.handler.codec.http2.StreamBufferingEncoder$Http2GoAwayException in a lot of requests

### ISSUE THREAD

**Issue by SmikeSix** [jchambers/pushy#1025]
Hi we rarely are sending ~300k of IOS push messages. 
Around 50% of them wont be delivered successfully, they are all active users.

We are receiving this error, for most of them:

```
io.netty.handler.codec.http2.StreamBufferingEncoder$Http2GoAwayException
	at io.netty.handler.codec.http2.StreamBufferingEncoder.cancelGoAwayStreams(StreamBufferingEncoder.java:253)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.access$000(StreamBufferingEncoder.java:59)
```

```java
                        tokenList.each { token ->
                            try {
                                def response =
                                        apnsClient.sendNotification(new SimpleApnsPushNotification(token, APNS_TOPIC_NAME, payload))

                                response.whenComplete({ pushNotificationResponse, throwable ->
```

pushNotificationResponse is null, throwable has the error. Is there a way to see what causes this error?

----

```
def concurrentConnections = 3

        return new ApnsClientBuilder()
                .setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
                .setClientCredentials(certificate.getInputStream(), password)
                .setConcurrentConnections(concurrentConnections)
                .setEventLoopGroup(new NioEventLoopGroup(concurrentConnections))
                .build()
```

Any idea in what kind of limit we are running? Is there a way to get more details on what causes the GoAway Exception?

Thanks!

**Comment by vominhtrius** [comment]
I have the same issue.
any idea?

**Comment by jchambers** [comment]
Please accept my sincere apologies for taking so long to get to this issue.

> Any idea in what kind of limit we are running?

In short, no.

> Is there a way to get more details on what causes the GoAway Exception?

Yes. Please see the Netty API documentation for [`Http2GoAwayException`](https://netty.io/4.1/api/index.html?io/netty/handler/codec/http2/StreamBufferingEncoder.Http2GoAwayException.html). You can inspect the inspection to get the [`errorCode()`](https://netty.io/4.1/api/io/netty/handler/codec/http2/StreamBufferingEncoder.Http2GoAwayException.html#errorCode--) and [`debugData()`](https://netty.io/4.1/api/io/netty/handler/codec/http2/StreamBufferingEncoder.Http2GoAwayException.html#debugData--), which you can often turn into a string.

At this point, I don't think there's any reason to believe this is an issue with Pushy itself (i.e. I don't think we could make a change to Pushy that would change this behavior). With that in mind, let's close this issue for now. If you learn more or have reason to believe that this is a problem with Pushy itself, please do not hesitate to open a new issue (if you think there's a bug) or discussion (if you just need help).

Thanks for your patience!
