### ISSUE TITLE
Native SSL provider is available; will use native provider.

### ISSUE THREAD

**Issue by sohabotros** [jchambers/pushy#1035]
Hello,
I am getting the following message "Native SSL provider is available; will use native provider." and when trying to send as notification, The sendNotification is returning a null.  

I tried to add the following to my build.gradle:
runtimeOnly 'io.netty:netty-tcnative-boringssl-static:2.0.36.Final'

But, when I do so, I get the following error when trying to setup ApnsClientBuilder: 
eanInstantiationException: Failed to instantiate [com.eatthepath.pushy.apns.ApnsClient]: Factory method 'apnsClient' threw exception; nested exception is java.lang.NoClassDefFoundError: io/netty/internal/tcnative/AsyncSSLPrivateKeyMethod","name":"org.springframework.beans.factory.BeanCreationException","cause":{"commonElementCount":20,"localizedMessage":"Failed to instantiate [com.eatthepath.pushy.apns.ApnsClient]: Factory method 'apnsClient' threw exception; nested exception is java.lang.NoClassDefFoundError: io/netty/internal/tcnative/AsyncSSLPrivateKeyMethod"

I'm using pushy version '0.15.1' together with jdk 11 within springboot framework (Tomcat container)

**Comment by jchambers** [comment]
It sounds like you're using a very outdated version of netty-tcnative-boringssl-static. The recommended version for Pushy 0.15.1 was 2.0.50.Final.

**Comment by sohabotros** [comment]
I add netty-tcnative-boringssl-static 2.0.50.Final to the project but I still get the message "Native SSL provider is available; will use native provider." and when trying to send as notification, The sendNotification is returning a null.  What else do I need to do for pushy to identify netty as SSL Provider?  

Any special considerations if the application is a springboot app running within a container environment?

**Comment by sohabotros** [comment]
Correction, the message I am getting is "Native SSL provider not available; will use JDK SSL provider"

**Comment by jchambers** [comment]
This sounds like more of a request for general technical support than a bug report. Let's move this to a discussion.
