### ISSUE TITLE
Missing "start" enumeration com.eatthepath.pushy.apns.util.LiveActivityEvent

### ISSUE THREAD

**Issue by soda-universe** [jchambers/pushy#1047]
The official apns documentation requires the event to be specified as start, but pushy does have this enumerated value.

https://developer.apple.com/documentation/activitykit/starting-and-updating-live-activities-with-activitykit-push-notifications#Construct-the-payload-that-starts-a-Live-Activity

What do you think about it?

**Comment by jchambers** [comment]
It looks like something changed upstream, likely with the latest iOS release. The old documentation link (https://developer.apple.com/documentation/activitykit/update-and-end-your-live-activity-with-remote-push-notifications) now redirects to the link you provided, and (strangely) makes no mention of the "end" event any more. It's unclear to me if this is a deliberate change or just a mistake in the documentation.

In any case, I've opened #1049 to add the "start" event type.

**Comment by soda-universe** [comment]
thanks!

**Comment by soda-universe** [comment]
hi， when is v0.15.4 expected to be released?

**Comment by soda-universe** [comment]
> It looks like something changed upstream, likely with the latest iOS release. The old documentation link (https://developer.apple.com/documentation/activitykit/update-and-end-your-live-activity-with-remote-push-notifications) now redirects to the link you provided, and (strangely) makes no mention of the "end" event any more. It's unclear to me if this is a deliberate change or just a mistake in the documentation.
> 
> In any case, I've opened #1049 to add the "start" event type.

thanks, when is v0.15.4 expected to be released?
