### ISSUE TITLE
add attributes-type and attributes to the payloadbuilder

### ISSUE THREAD

**Issue by JO0st** [jchambers/pushy#1050]
In the [documentation for remote starting a live activity](https://developer.apple.com/documentation/activitykit/starting-and-updating-live-activities-with-activitykit-push-notifications#Construct-the-payload-that-starts-a-Live-Activity) it is mentioned that the attributes and attributes-type keys should be present in the payload when starting a live activity. These are not available in the payload builder yet.

**Comment by jchambers** [comment]
I'll address this.

While neither actionable nor constructive, I have to say that I am beginning to get annoyed with the lack of centralized documentation for what can or should be in payloads these days; it's all just mentioned in passing in documentation for other features.

**Comment by JO0st** [comment]
Thank you very much for adding this. You were faster at it then I could pick it up myself.
