### ISSUE TITLE
Allow methods to not require passing a privateKeyPassword

### ISSUE THREAD

**Issue by Guergeiro** [jchambers/pushy#1067]
When using `setClientCredentials` or `setServerCredentials` it is required to pass `privateKeyPassword` as the 3rd argument even when not required. The documentation states that in case no `privateKeyPassword` is set, we should pass `null`. Can't we improve the API by having a method overload for those cases?

Example pseudo-code
```
setServerCredentials(certificatePemFile, privateKeyPkcs8File) {
    super.setServerCredentials(certificatePemFile, privateKeyPkcs8File, null);
}
```

This wouldn't break any existing logic.

**Comment by jchambers** [comment]
Sure: #1072
