### ISSUE TITLE
0.15.4 with jdk 8 error

### ISSUE THREAD

**Issue by 3210439** [jchambers/pushy#1069]
Hi,

I am currently using Maven, JDK 8.0.382-zulu, and Pushy 0.15.4. However, I encountered an issue.

When I inspect the ApnsClient.class file, I receive the following message: Decompiled .class file, bytecode version: 52.0 (Java 8). This is unexpected because I am using Java 8.

To troubleshoot, I upgraded my Java version to 17.0.8-amzn, but the problem persists. As a temporary workaround, I reverted to Pushy 0.15.2, which resolved the issue.

Could you provide guidance or a permanent fix for this problem?

Thank you.

**Comment by jchambers** [comment]
> Decompiled .class file, bytecode version: 52.0 (Java 8). This is unexpected because I am using Java 8.

I don't mean to be difficult, but I don't think I understand the problem. Can you please say more?

Pushy does, indeed, target Java 8, so 52.0 is the bytecode version I'd expect. Why would you expect your JVM version to change the version of the compiled bytecode?

**Comment by jchambers** [comment]
@3210439 I'm pretty sure there's nothing wrong here, and am going to take the optimistic step of closing this ticket for now. If you have an opportunity to explain the problem in more detail, please post a comment here and I'll happily revisit the issue!
