### ISSUE TITLE
How to implement VoIP Notification using Pushy

### ISSUE THREAD

**Issue by kumarlav0** [jchambers/pushy#1077]
In my iOS [ Swift ] app there is feature to receive voice and video calls. 
So, for normal notification Pushy is used. Now I want to get VoIP notification from my server for Voice & Video calls. 
So that I can use CallKit easily to show Calling feature and UI when My App is in killed state, Background state and in Foreground state.

Please help me to find any way to do this using Pushy. or Is it possible with Pushy or not ?

**Comment by jchambers** [comment]
VOIP push notifications are just normal push notifications to a VOIP-specific topic. Pushy does support VOIP notifications (because they're no different from any other kind of notification). Please see https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns.

**Comment by kumarlav0** [comment]
Ok, Thank you @jchambers  for your response.

**Comment by kumarlav0** [comment]
Hi @jchambers  I have one more thing I would like to confirm: Is a .p8 or .p12 file required for implementing normal push notifications using Pushy on the server side?

**Comment by jchambers** [comment]
I don't entirely understand the question. You need to present some kind of credentials; that can be either a signing key or a client certificate.

That said: this sounds like a request for general technical support. Going forward, could you please [open a new discussion](https://github.com/jchambers/pushy/discussions/categories/q-a) for questions like this (as opposed to opening an issue)? Thanks!
