### ISSUE TITLE
Need a way to send APNS notification with fresh authentication

### ISSUE THREAD

**Issue by kkolyan** [jchambers/pushy#1087]
Discussion was started in https://github.com/jchambers/pushy/pull/1086, but it was closed without me having an opportunity to prove my point. Seems like there are no notifications on closed PRs, so I'm creating issue to continue dialog.

### Short:
 the problem is: we need to periodically check health of admin settings by sending dummy notifications with fresh authentication. The best way we see (please point if there are better ones) is to create new ApnsClient for each dummy notification. The problem of this approach is that SslContext creation in our environment is very CPU-expensive.

### Long
https://github.com/jchambers/pushy/pull/1086#issuecomment-2444424560

### Continue of discussion

PR was rejected due to two reasons:
1. the connection of my problem with SslContext CPU costs looks doubtful.
2. my case is not common enough to address it in mainstream.

If the `point 2` is enough for you to close this discussion, then ok, I have to deal with it somehow on my side.

But if the power of `point 2` is enough only in a shadow of `point 1`, then please evaluate my arguments.

### SslContext creation can be expensive

Cost of SslContext creation depends on specific algorithms it use and its parameters. Probably, I should've said it earlier, but we use use FIPS-ed JVM due to customer security requirements, so the set of cryptographic algorithms and its parameters (key lengths for instance) is different from the ones you use in the mentioned benchmark. And probably, the one we use makes SslContext creation much more (10000x in this case) slower that default ones you used.

The logs shows that SslContext creation requested ~100 times per minute:
![image](https://github.com/user-attachments/assets/20970352-dfb8-41cf-8db3-7156cace9fa3)

Flamegraph (recorded during 5 minutes) shows that SslContext creation in ApnsClientBuilder is almost the only thing this JVM do (that's test env and no tests are running):
![image](https://github.com/user-attachments/assets/8ab2d0c6-624c-4b49-92b0-11b4e51da81d)

CPU metrics shows that in this mode it takes ~0.3 cpu:
![image](https://github.com/user-attachments/assets/ba484795-a2b1-4cd5-8944-e2065c26c28d)

**Comment by jchambers** [comment]
> …it was closed without me having an opportunity to prove my point. Seems like there are no notifications on closed PRs, so I'm creating issue to continue dialog.

Friend, with respect, this is simply not true. You have not been silenced, and I am receiving notifications. I just didn't respond immediately because I've been busy. I understand that this is important to you, but I do need to focus on other things right now. I will engage with the issue in detail when I have the capacity to do so some time in the next couple days. Until then, I appreciate your patience.

Because there's already a conversation about this issue, let's close this one and keep things in one place.
