### ISSUE TITLE
Update Trust Store for new SHA-2 Root

### ISSUE THREAD

**Issue by kennardconsulting** [jchambers/pushy#1093]
Thanks so much for developing Pushy. It's been a huge help to our project!

I just received this e-mail from Apple. I assume this is something Pushy needs to handle for us?

---

> As we announced in October, the Certification Authority (CA) for Apple Push Notification service (APNs) is changing. APNs will update the server certificates in sandbox on January 20, 2025, and in production on February 24, 2025. To continue using APNs without interruption, you’ll need to update your application’s Trust Store to include the new server certificate: [SHA-2 Root : USERTrust RSA Certification Authority certificate](https://c.apple.com/r?v=2&a=o2CKfLM8dAL7lynfnyn7UJR94mniF31x6BQ8mUoKnZUmrEJND4j4StB1ZMXo8GN0HHVu0pJbMaVrdNz2o%2BEnhMb2NNLXlOL%2FmVXqAEtn8EKuH%2FFM9rFnUnv42axncWRxMeXAnmySS9duY3TqHXJJYxHAON1uLC1xOXV5gJVhN0PBMYiJH2fiWz%2B5WujGhjIzOJeCCbIeYqg3EyxK7CmAxQlCLzUwBWEALXtsBG6u9TyAljvFA%2FJIhAeQ3JJJYI7Rhti8CER4NgWxHjdreD%2B9ECtJG1f%2Fos9Dsmom90mfWWY%3D)
>
> To ensure a smooth transition and avoid push notification delivery failures, please make sure that both old and new server certificates are included in the Trust Store before the cut-off date for each of your application servers that connect to sandbox and production. At this time, you don’t need to update the APNs SSL provider certificates issued to you by Apple.

**Comment by jchambers** [comment]
> I assume this is something Pushy needs to handle for us?

No; this is something you'll need to do for yourself. Your trust store is outside of Pushy's control (for good reason!). That said, the new certificate is likely already in your trust store.

Let's move any additional questions over to the existing discussion (#1085), which also has detailed instructions for checking whether you need to take any action.
