### ISSUE TITLE
Support for using Jackson instead of Gson

### ISSUE THREAD

**Issue by filiphr** [jchambers/pushy#678]
Currently the `ApnsPayloadBuilder` uses Gson to create the content for the payload. 

Is it possible to make the creation of payload pluggable via some kind of interface, or extract a base builder that would have common methods for the locations where the conversion to JSON is needed?

The reason why I am asking for this is due to the fact that I would like to try and use one JSON parsing library within our project and currently we use Jackson a lot.

I am also prepared to work on this if you are interested and would accept such a PR.

**Comment by jchambers** [comment]
I think that's a reasonable suggestion, but I'd definitely want to find a way to do it that doesn't introduce more complexity when end users add Pushy as a dependency. A bad outcome, in my mind, would be having Pushy fail to produce payloads at runtime because somebody doesn't have any JSON libraries on their classpath.

Let me think on some strategies; I'm very open to suggestions!

**Comment by filiphr** [comment]
In order to be backwards compatible I was thinking to continue having Gson as a compile dependency like you are doing now. And have an optional dependency on `Jackson` (unless you decide to force users to define a dependency). Otherwise, you have the risk that people will start to have problems, because you don't have a dependency. If you want you can provide a maven dependency that would exclude Gson and use Jackson in it (just a decorative pom).

In terms of implementation I was thinking to add something like `PayloadConverter` (naming can be whatever). 

That looks like:

```java
public interface PayloadConverter {

    // both Gson and Jackson support something like this
    String writeJsonPayload(Writer writer, Object value); 
}
```

Then there will be a `GsonPayloadConverter` and a `JacksonPayloadConverter`.

The `ApnsPayloadBuilder` will then have the payload converter field initialized in the constructor, and there can be an optional constructor where you can pass the converter. Additionally you can have some class that would provide the default converter based on the runtime classes. For example if you have Gson then Gson would be used, if you have Jackson then Jackson would be used. It is up to you to decide which one has preference (not sure which one is faster).

In the `ApnsPayloadBuilder` all the places that use the static `GSON` to just call the `payloadConverter#writeJsonPayload(Writer, Object)`.

**Comment by jchambers** [comment]
Please excuse the long delay in getting back to this.

> I was thinking to continue having Gson as a compile dependency like you are doing now.

Respectfully, if we still have Gson as a dependency, why does it matter if we're using Gson or Jackson to generate the payload? Is the idea that you'd then add an `exclude` clause for Gson if you really, really didn't want it?

**Comment by filiphr** [comment]
>Please excuse the long delay in getting back to this.

No problem. 

>Respectfully, if we still have Gson as a dependency, why does it matter if we're using Gson or Jackson to generate the payload? Is the idea that you'd then add an exclude clause for Gson if you really, really didn't want it?

Yes the idea was that you can explicitly exclude Gson if you don't need it. However, it depends on the approach you'll like to take.

Here are some options that I have in mind:

* Do not to include any library and have a manual way of crafting the payload in case none are present
* Request from users to include a library
* Add 2 new artifacts that would either include Gson or Jackson as a dependency. If you want full backwards compatibility you can just add a Jacskon one that would exclude Gson and add Jackson

**Comment by bound2** [comment]
+1 for this idea. It's very important that the json serialization is uniform across the project.

**Comment by jchambers** [comment]
I've proposed #744 as a first step in a larger refactoring effort to make JSON serialization more flexible; feedback is welcome!

**Comment by jchambers** [comment]
Also, as I'm thinking about this more, it seems like Pushy is going to have to depend on _some_ JSON library for its own purposes (especially around authentication token handling). I think that means it's going to have a required dependency on (for example) GSON no matter what, but we should be able to get to a place where folks can _also_ use something else for payload construction.

**Comment by jchambers** [comment]
This is covered by #776.
