### ISSUE TITLE
Double promise mark warning in case of bad certificate

### ISSUE THREAD

**Issue by eugeneseppel** [jchambers/pushy#693]
If caller provides "bad" certificate to Pushy (i.e. certificate that causes CERTIFICATE_AND_PRIVATE_KEY_MISMATCH or SSLV3_ALERT_CERTIFICATE_REVOKED SSL error) pushy logs following warning:

> WARN  [apns-push-6] [2019-04-11T12:07:55.911Z] [c.t.p.a.ApnsChannelFactory] [] [] [] [] Tried to mark promise as "failed," but it was already done.

It seems to be a design problem, but more important that service logs are filled by warnings that look to be pointless (this problem have to be resolved and/or logged by caller)

**Comment by jchambers** [comment]
Can you provide more context? Is there a stack trace available? Do you know which future is affected?

**Comment by eugeneseppel** [comment]
I'm currently dealing with this issue and it seems to be bit complicated.
Software versions: 
Pushy 0.14
Netty 4.1.34.Final (I've experienced this issue with previous versions as well
netty-tcnative-boringssl-static 2.0.25.Final
O/S: Amazon Linux AMI 2017.09 and Ubuntu Linux 18.04
Native *ssl* packages openssl-1.0.2k-8.107.amzn1.x86_64 and 1.1.0g-2ubuntu4.3 respectively. I have no ideas whether they are used.

Client provides bad certificate+key. One can reproduce this by providing key for different certificate, or by providing key+cert that are already revoked in Apple console.

Every time this causes the following warning:

> 
> WARN  [apns-push-1] [2019-04-18T10:45:23.529Z] [c.t.p.a.ApnsChannelFactory] [] [] [] [] Tried to mark promise as "failed," but it was already done.
> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000414:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_REVOKED
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: javax.net.ssl.SSLHandshakeException: error:10000414:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_REVOKED
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:973)
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1231)
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1185)
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1256)
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1299)
> 	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:217)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330)
> 	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	... 17 common frames omitted

I've added some more logic to test what's going on (changed that error message to provide more details
and added print stack trace):
> Tried to mark promise as "failed," with cause='io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000414:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_REVOKED', but it is already 'Failed' with cause='javax.net.ssl.SSLHandshakeException: error:10000414:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_REVOKED'

First call:

> java.lang.Exception: Stack trace
> 	at java.lang.Thread.dumpStack(Thread.java:1336)
> 	at com.turo.pushy.apns.ApnsChannelFactory.tryFailureAndLogRejectedCause(ApnsChannelFactory.java:264)
> 	at com.turo.pushy.apns.ApnsChannelFactory.access$100(ApnsChannelFactory.java:56)
> 	at com.turo.pushy.apns.ApnsChannelFactory$1$1.operationComplete(ApnsChannelFactory.java:162)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
> 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
> 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
> 	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1249)
> 	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1239)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

This means that tryFailureAndLogRejectedCause was invoked in last "else" of listener "sslHandler.handshakeFuture().addListener(new GenericFutureListener<Future<Channel>>() "

Second call: 

> java.lang.Exception: Stack trace
> 	at java.lang.Thread.dumpStack(Thread.java:1336)
> 	at com.turo.pushy.apns.ApnsChannelFactory.tryFailureAndLogRejectedCause(ApnsChannelFactory.java:264)
> 	at com.turo.pushy.apns.ApnsChannelFactory.access$100(ApnsChannelFactory.java:56)
> 	at com.turo.pushy.apns.ApnsChannelFactory$ConnectionNegotiationErrorHandler.exceptionCaught(ApnsChannelFactory.java:80)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:282)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:261)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:253)
> 	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1096)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:282)
> 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:820)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:361)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
It means method was invoked by ConnectionNegotiationErrorHandler::exceptionCaught

But basically this warning is a half of evil. Sometimes with same condition (same certificates) I experience much serious issue with SSL. I can't reproduce this error and it appears only several times per day on AWS box.  Some error appears at SSL level, HTTP/2 connection is dropped during preface and following errors are logged:

One:
> [sendNotification] PushFailure, status='FAIL' apnsError='None' message='Failed to dispatch message to APNS, reason: Channel closed before HTTP/2 preface completed.' apnsId='e5c38271-ffc4-25ad-766e-34a6b11b96ae' cause='java.lang.IllegalStateException', cause.message='Channel closed before HTTP/2 preface completed.'
> It means that in ApnsChannelFactory:229 the connectFuture.channel().closeFuture().addListener(new GenericFutureListener<ChannelFuture> ()::operationComplete is invoked with IllegalStateException 
> 


Two:

> WARN  [apns-push-5] [2019-04-17T21:22:03.162Z] [i.n.c.ChannelInitializer] [] [] [] [] Failed to initialize a channel. Closing: [id: 0xdfc9280f]
> java.lang.NullPointerException: ctx
>         at io.netty.internal.tcnative.SSL.newSSL(Native Method)
>         at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:338)
>         at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine0(ReferenceCountedOpenSslContext.java:419)
>         at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newHandler(ReferenceCountedOpenSslContext.java:399)
>         at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:888)
>         at com.turo.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:119)
>         at com.turo.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:109)
>         at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
>         at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
>         at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:953)
>         at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
>         at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
>         at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
>         at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
>         at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> INFO  [apns-push-0] [2019-04-17T21:22:03.162Z] [c.t.r.a.v.s.TwilioApnsClient] [RQ6e428e46b9cf41d0bc028b2ef36bde53] [RU5c797e6006dba154e874b4a9b6ee986b] [ACf5eaf92c0dbeb386aed1e01b353bd92e] [sendNotification] sendNotification: message='APNs future completed' latency='1064'

It looks like some problem with native SSL.

**Comment by eugeneseppel** [comment]
But I have to add that before migrating to new pushy (from pushy 0.12)
we experienced from time to time such exceptions:
exception='java.nio.channels.ClosedChannelException'
exception='javax.net.ssl.SSLException: SSLEngine closed already'
I have no log and stacktraces for old code

**Comment by jchambers** [comment]
Thank you for the additional information. We'll look into it.
