### ISSUE TITLE
Be able to configure Gson builder.

### ISSUE THREAD

**Issue by amir20001** [jchambers/pushy#696]
I'm personally running into an issue with date formatting but the same idea applied to any of the configs.

it would be nice if I could set my own Gson

**Comment by jchambers** [comment]
This sounds like it's closely related to #678. We'll give it some thought.

**Comment by amir20001** [comment]
@jchambers sorry about the delay. I would say the desired behaviour is pretty similar to #678, but I think the amount of work required to do it is quite different.

**Comment by jchambers** [comment]
I've proposed #744 as a first step in a larger refactoring effort to make JSON serialization more flexible; feedback is welcome!

**Comment by jchambers** [comment]
This is covered by #776.
