### ISSUE TITLE
Android pushes is not coming to device

### ISSUE THREAD

**Issue by CrackerakiUA** [jchambers/pushy#761]
With latest version of pushy, I have ios release which works smoothly and android which don't receive pushes. Register device works, `Pushy.listen` function exists and called normally. What can we do about that, how can we debug that?

**Comment by jchambers** [comment]
Hi, friend! I'm afraid you may have us confused with https://pushy.me/, which is an entirely separate organization and piece of software.

**Comment by CrackerakiUA** [comment]
omg, indeed. Sorry.

**Comment by jchambers** [comment]
No worries at all! This happens way more often than you'd think.
