### ISSUE TITLE
Use one date serialisation method

### ISSUE THREAD

**Issue by AaronBedward** [jchambers/pushy#762]
Currently using Jackson in my spring project and noticed you are using GSON - i've seen the other issues and the imminent refactor however the following line is causing a bit of a hassle as Instant  type is serialised across the project.

As a simple fix use the same method to create GSON across all instances.

./util/ApnsPayloadBuilder.java

```
 private static final Gson GSON = new GsonBuilder().serializeNulls().disableHtmlEscaping().create();
```

and in ./auth/AuthenticationToken.java

```
 private static final Gson GSON = new GsonBuilder()
            .disableHtmlEscaping()
            .registerTypeAdapter(Instant.class, new InstantAsTimeSinceEpochTypeAdapter(TimeUnit.SECONDS))
            .create();
```

Any thoughts or a quick fix?

**Comment by jchambers** [comment]
Your point is taken, but I think the best approach is to roll this in with a larger JSON overhaul (see #678 and #696). I'm going to close this issue for now because I think the substance is pretty much captured in those other two tickets.

Cheers, and thanks for the suggestion!
