### ISSUE TITLE
Docs mention "whenComplete", but it isn't available

### ISSUE THREAD

**Issue by evertson90** [jchambers/pushy#766]
Hi, 

I'm using the 0.13.11.jar of the Pushy library and I want to use then "whenComplete" method that is mentioned in the example, however it is not available on the PushNotificationFuture. I'm guessing this is because it extends Future and not CompletableFuture. Why is it still present in the docs example?

**Comment by evertson90** [comment]
Oh, I see that in the code checked in here it DOES extend CompletableFuture. I guess I just need to use the snapshot. I'm closing this issue.

**Comment by jchambers** [comment]
Yeah—it's always a little tricky to strike the balance between "we should keep the README up to date with recent changes" and "the README should reflect what's going on in the latest release." As you've discovered, this is a case of the former. I suppose I _could_ set the default branch to the latest release, but that's caused a lot of confusion in the past, too.

The point is: I acknowledge the issue, but will observe a little while longer before making any changes to the README strategy.

Thanks for your patience!

**Comment by sirghi** [comment]
I also was confused about this. Might be worth doing releases more often in that case. Anything blocking a new release at the moment?
