### ISSUE TITLE
No way to directly compare getRejectionReason() to a RejectionReason

### ISSUE THREAD

**Issue by MF1-MS** [jchambers/pushy#771]
In our code where we handle the result of a `PushNotificationResponse` we want to log different things / bump different stats based upon the rejection reason we can extract with `PushNotificationResponse.getRejectionReason()`. However there is no way to compare the returned String directly to the values of `RejectionReason` defined in pushy as `RejectionReason.getReasonText()` is only visible at a package scope. This means we have had to define our own String constants to match what we expect APNs to return.

Clearly we'd rather match against the pushy library enum instead of duplicating that effort, would we be able to make the `RejectionReason` getters public?

**Comment by jchambers** [comment]
Hello! I certainly understand where you're coming from, but keeping `RejectionReason` package-private is actually a deliberate decision. Please see #650 for prior discussion and rationale. I'll close this ticket for now, but am certainly open to new arguments!

**Comment by MF1-MS** [comment]
Oh, I did have a quick search through the previous issues but didn't spot this had been raised before sorry! 

I fully agree that the transient nature of the APNs API means that we need `getRejectionReason()` to return a string as opposed to risking forcing it into a potentially invalid enum. But any change to the API will require integration work for anyone matching on those responses, enum or not, so I don't follow how having public getters on `RejectionReason` does anything other than potentially reduce duplication of work?
