### ISSUE TITLE
Feature Request: buildWithDefaultMaximumLength in 0.14.0

### ISSUE THREAD

**Issue by mohamedhafez** [jchambers/pushy#779]
For the new `ApnsPayloadBuilder` classes in 0.14.0, there's no more `buildWithDefaultMaximumLength` method. It was a really nice feature to have the payload message truncated only as much as needed to get it down to the 4096 byte limit, just my vote to see if others also would like to have it back.

Either way, thanks for all the hard work on this library, it's much appreciated!

**Comment by jchambers** [comment]
Respectfully, do you actually have a use case where you're sending payloads with messages longer than 4,096 bytes? Could you give me more context to help understand the need?

**Comment by mohamedhafez** [comment]
Sure, so my app sends out notifications of new job postings to substitute teachers, along with a "Book" button they can click to book the job. Sometimes these postings have special instructions from the teacher. 99.9% of the time its not even close to the 4096 byte limit, but every now and then you get a teacher that's written a few paragraphs, and it needs to be truncated to fit in the notification. It can be important to include those special instructions because sometimes there's something in it that would make a substitute not want the job or not be eligible for it, although to be fair when that's the case those special instructions are usually pretty short.

In my case I'm just working around the issue by limiting the size of the special instructions field to 3000 bytes, and I don't think any customers will care that much, so it's not a big deal or anything, it would just be nice to be able to include the maximum amount allowed. It's not quite as trivial as just counting how many extra characters you have and subtracting them from the payload message, since some characters would need to be escaped and thus take 2 bytes, etc, and I was thinking that maybe there are others in similar situations where it would be a nice feature to have. 

But, like I said it's not even that big a deal in my case, and if there are really super few of us that would actually benefit from the feature then of course don't worry about it, I just thought I'd throw it out there.

**Comment by jchambers** [comment]
Thanks for clarifying!

I think we'll stick with the current decision for a few reasons:

1. I strongly suspect this is a less common case.
2. The only thing the old `ApnsPayloadBuilder` would actually shorten was the literal alert text; I'm not aware of any device that would show anywhere close to 4096 bytes of text before eliding it (ignoring long-press expansion).
3. There are solid workarounds if really, positively need to post a >4kB alert, like sending a background notification and letting the app fetch the data and construct a local notification with the expanded payload.

I appreciate your time in explaining the use case, and thanks for the feedback!
