### ISSUE TITLE
Does / will this support apns-push-type

### ISSUE THREAD

**Issue by pkasson** [jchambers/pushy#790]
I have been using import com.notnoop.apns.APNS for some time ... works great, still does.

It is seemingly no longer maintained they their repo pointed us to you - lucky you !

According to what I have read, this will be a requirement in the header very soon, or notifications may get dropped or ignored:   apns-push-type

Is this going to be added to the base ?

Thanks !

**Comment by jchambers** [comment]
Support for `apns-push-type` has been in place for a while now. Please see [`ApnsPushNotification.html#getPushType()`](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/ApnsPushNotification.html#getPushType()) for the general interface and [`SimpleApnsPushNotification(..., PushType)`](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/util/SimpleApnsPushNotification.html#%3Cinit%3E(java.lang.String,java.lang.String,java.lang.String,java.time.Instant,com.eatthepath.pushy.apns.DeliveryPriority,com.eatthepath.pushy.apns.PushType)) (for example) for creating a `SimpleApnsPushNotification` with a specific push type.

**Comment by pkasson** [comment]
Awesome - thank you - will try it out.
