### ISSUE TITLE
Transmission QoS for connections

### ISSUE THREAD

**Issue by jasonjoo2010** [jchambers/pushy#792]
Hi, Jon

Long time not here. I used to fire an issue name resolving related and a pr on it though they were not accepted 😄 Do you remember it?

I have an internal maintained branch based on pushy-0.10.x which integrates with our pushing service. It pushes up to 20k messages out from cluster having 4 nodes or more. It worked well as expected for quite a long time.

But recently we have big problem on it. The efficient addresses we could get from several dns servers  become less and less which means it won't work fine as before with "a little luck". Maybe the cause is pointing to some political reasons or other. But life has to move on.

So my initial design dealing the new situation is:

1. Build and maintain an address pool outside pushy as before.
2. Introduce statistics to every connection on send, response time, success, etc. for 1s, 5s, 60s for instance.
3. Evaluate the quality of every connection by efficiency on throughput or other metrics.
4. Kick out "significantly" poor connections from active list and try to get new one.
5. Limit messages in the air by connection instead of globally (Use semaphore for instance). Ensure stuck connection won't make things worse.

This time i want make it based on codes up to date. So i want to figure out (above proposal) whether it makes sense for official implementation or we can discuss it more.

Surely things will become more simple if we provide a pure or lite client implementation which is 1 connection to 1 client. It allows various logics outside and we only keep it simple and efficient.

**Comment by jchambers** [comment]
I know I'm sailing right past the bulk of your feature request, but if you're using a fork based on 0.10 and are experiencing connection degradation over time, I'm guessing you're affected by some upstream behavior changes (see #732). We put out a fix for that issue in [0.13.11](https://github.com/jchambers/pushy/releases/tag/pushy-0.13.11).

Could you please try updating to the latest version of Pushy (currently 0.14.1) and seeing if the problem persists? Thanks.

**Comment by jasonjoo2010** [comment]
> I know I'm sailing right past the bulk of your feature request, but if you're using a fork based on 0.10 and are experiencing connection degradation over time, I'm guessing you're affected by some upstream behavior changes (see #732). We put out a fix for that issue in [0.13.11](https://github.com/jchambers/pushy/releases/tag/pushy-0.13.11).
> 
> Could you please try updating to the latest version of Pushy (currently 0.14.1) and seeing if the problem persists? Thanks.

I had noticed your new pr at that time and tried it but things didn't turn better. I made conclusions after that:

1. A set of connections are created together when it comes to work.
2. It surely relies on realtime name resolving when creating.

So not so much addresses are used (typically 1 or 2 between 32 or 128 connections when experimenting).

Even assume it works and dozens of addresses are resolved to create these connections but it will have exactly the same effect as what our internal service get. So maybe it won't work too because it's still a `passive` way. We are now designing an active way to make the connection table more healthy. (Which is more like a static table in current design if connections can just be kept established)

It's a bit complicated. I don't know whether i make things clear. Life is too hard for IT guys in china. :(

**Comment by jasonjoo2010** [comment]
I found an alternative way that we can implement a proxy locally deployed like a sidecar. Connection cutter can be done in the proxy. We will have a try on it.

Pushy has been updated to 0.14.1 and several points have been improved. Especially leak of semaphores doesn't happen again since updated.

If any further news i will update it back. Thank you, Jon.

**Comment by jchambers** [comment]
Don't feel like I contributed much here, but I'm glad you've found a way forward! Please do let us know how it goes!

**Comment by jasonjoo2010** [comment]
> Don't feel like I contributed much here, but I'm glad you've found a way forward! Please do let us know how it goes!

Nice! Travel lasts and we all are accompaniers :)
