### ISSUE TITLE
Getting javax.net.ssl.SSLHandshakeException: No appropriate protocol while trying certificate based approach

### ISSUE THREAD

**Issue by umail2deepak** [jchambers/pushy#798]
Hi All,

I am trying to implement cert based HTTP2 APNS Notifications. I am using a spring application with pushy(0.13.12). I am running this application on weblogic 12c with Java 1.7.  I have been using ApnsClient.sendNotification() method with SimpleApnsPushNotification. I am getting this error on line  sendNotificationFuture.get();. As I am using a proxy server I am also using builder.setProxyHandlerFactory(new HttpProxyHandlerFactory(new InetSocketAddress(proxyHost, proxyPort)));.
Below is full builder code:
     if (production) {
            builder.setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST);
        } else {
            builder.setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST);
        }
       builder.setProxyHandlerFactory(new HttpProxyHandlerFactory(new InetSocketAddress(proxyHost, proxyPort)));

I would also like to know lets say there are cases when my app can send notification to invalid-device-tokens(old-tokens). Initially I was using com.notnoop.apns - apns api through which we can register a delegate(builder.withDelegate(entitiesDeviceDetailsInvalidatingApnsDelegate);) Can we do something similar in pushy as well. I want to cleanup all those old-tokens if notification fails.

**Comment by jchambers** [comment]
Pushy 0.13 requires `netty-tcnative` (or some other JCA like Bouncy Castle) if you're using Java 7. Please see the README for instructions.
