### ISSUE TITLE
Provide alertTitle and localizedAlertTitle in ApnsPayloadBuilder

### ISSUE THREAD

**Issue by dtechen** [jchambers/pushy#799]
Is there any specific reason why setting the alertTitle on https://github.com/jchambers/pushy/blob/master/pushy/src/main/java/com/eatthepath/pushy/apns/util/ApnsPayloadBuilder.java wipes out the localizedAlertTitle and vice versa? According to our tests, Apple seems to support providing both at the same time. It is important to us to provide both in order to keep our server compatible to older versions of the app.

Best,
Daniel

**Comment by jchambers** [comment]
In the past, the documentation described them as mutually exclusive. That may have changed. I'll look into it.

**Comment by dtechen** [comment]
Thanks for looking into it. Could you find out anything in the meantime? I personally find apple's documentation somewhat limited on this topic.

**Comment by Anddor** [comment]
AlertTitle will work as a fallback for apps that do not have the localization key in the strings file (subtitle and body work the same way), altough I am not sure which iOS versions started this behaviour. I have created a pull request to implement setting both loc key and explict value, does the approach look ok? https://github.com/jchambers/pushy/pull/851

I guess the alternative is to remove setting the other to null, so one would just set both in ApnsPayloadBuilder to support fallback?
