### ISSUE TITLE
Consider using RejectionReason enum in PushNotificationResponse

### ISSUE THREAD

**Issue by petrdvorak** [jchambers/pushy#800]
Currently, the rejection reason is returned as a String, which disallows efficient handling of all cases using a switch-case block. It would be nice to have some type of typed value there or at least a hint in the docs on how to evaluate rejection reasons...

**Comment by jchambers** [comment]
Hello! I certainly understand where you're coming from, but keeping RejectionReason package-private is actually a deliberate decision. Please see #650 for prior discussion and rationale. I'll close this ticket for now, but am certainly open to new arguments!
