### ISSUE TITLE
send will not fire when targeting a single user, unless explicitly call Fulture.get() . Under version 0.14.1

### ISSUE THREAD

**Issue by liuxu0703** [jchambers/pushy#802]
I am following instructions from The Best Practice, and introduced Semaphore to control the flow. The sending part is exactly the same as in [The Best Practice](https://github.com/jchambers/pushy/wiki/Best-practices#flow-control):

```
semaphore.acquire();
final CompletableFuture<PushNotificationResponse> sendFuture = apnsClient.sendNotification(pushNotificationSource.next());
sendFuture.whenComplete((response, cause) -> {
    // Do whatever processing needs to be done
    semaphore.release();
});
```

When targeting for a group of users, it works perfectly well. But when pushing only to one user, it did not work: action in `whenComplete()` never get called, and the IOS device never get the message.

Further tries show that if we call `Future.get()`, it would work:
```
apnsClient.sendNotification(pushNotificationSource.next()).get();
```

We tried to add break point in the code, and found that `this.channelPool.acquire().addListener(...)` in function `ApnsClient.sendNotification()` would not callback if `Future.get()` is not called.
We also tried to push to just 2 user, the first we call `Future.get()`, the second we do not, and both user can get the message:
```
AtomicInteger count = new AtomicInteger(0);

......

if (count.incrementAndGet() == 1) {
    apnsClient.sendNotification(pushNotificationSource.next()).get();
} else {
    apnsClient.sendNotification(pushNotificationSource.next());
}
```

Thanks in advance.

**Comment by wrglive** [comment]
When I single-push, there are often scenes of message accumulation, and then looking at the source code, I feel that the semaphore tool may not be successfully released due to the incorrect call of the callback function, so today I switched to ratelimiter to try the effect.

**Comment by liuxu0703** [comment]
Thanks. Do you have any advice about single push? About the message accumulation, how many accumulated messages must be there to trigger a push?
I also noticed the `sendFuture.whenComplete()` in semaphore best practice example call may replace the callback inside `ApnsClient.sendNotification()` function: `responseFuture.whenComplete((response, cause) -> {...})`. I think if I do not rely on `ApnsClientMetricsListener`, there would be no problem for me, but that would still be a problem.

**Comment by wrglive** [comment]
@liuxu0703  你是中国人吧?   可以加下qq 沟通下这个问题,   503713416

**Comment by liuxu0703** [comment]
> @liuxu0703 你是中国人吧? 可以加下qq 沟通下这个问题, 503713416

你的QQ有验证呀, 我加不上.

**Comment by liuxu0703** [comment]
> I'm confused as to how this could be happening, but my strong suspicion is that the client is getting closed before the notification can get sent. How are you shutting down the client in the single-notification case?

I think the problem may not be the closure of client, since we are now only at testing phrase. We just start up the application and then push straight forward, without delay. The close client logic is not yet in our code.
Thanks for the advise anyway, we will check if the client setup logic would somehow cause unexpected closure.
Also I am confused as to how `Future.get()` could influence the client, I checked the code and did not the connection.

**Comment by jchambers** [comment]
It sounds like we're mutually-confused ;)

Can you share a minimal test case that reproduces this problem?

**Comment by jchambers** [comment]
@liuxu0703 To clarify: I'm not able to reproduce the problem with any of the examples you provided in the description of the issue, and so I suspect there's some difference between how you and I are setting things up before getting to the "core" of the examples. If you can provide a complete, runnable, and minimal test case that reproduces the problem, I'm confident we can solve it. As things stand right now, though, I'm not able to reproduce this issue at all.

**Comment by huangjunchao** [comment]
I hava the same problem 

can not reveive example:

> final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                future1 = apnsClient.sendNotification(pushNotification);
        final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                future2 = apnsClient.sendNotification(pushNotification);

        sendNotificationFuture.whenComplete((response, cause) -> {
                if (response != null) {
                    System.out.println(response);
                }
        });

both future1 future2 can not reveive msg

can reveice example:

>  final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                sendNotificationFuture = apnsClient.sendNotification(pushNotification);
        final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                sendNotificationFuture1 = apnsClient.sendNotification(pushNotification);

        final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                sendNotificationFuture.get(20000, TimeUnit.MILLISECONDS);
        sendNotificationFuture.whenComplete((response, cause) -> {
                if (response != null) {
                    System.out.println(response);
                }
        });
both future1 future2 can reveive msg

**Comment by jchambers** [comment]
@huangjunchao I've copied/pasted your example into a unit test in the [`test-802` branch](https://github.com/jchambers/pushy/compare/test-802) and the test passes. I am still unable to reproduce the problem.

What I need from you (or anybody else in this thread) at this point is either:

1. A unit test that I can run that demonstrates this problem or
2. A complete, executable Java application that demonstrates this problem. The examples provided aren't enough; if you want to take this approach, I need a complete (but minimal!) application that compiles and runs. If it doesn't have `public static void main`, it's not a complete example.

Thank you for your help in getting to the bottom of the problem.

**Comment by huangjunchao** [comment]
very thinks to send email to me! I run you test https://github.com/jchambers/pushy/compare/test-802 is not problem too!

Abnormal scene

1. do not call countDownLatch.await() the apps can not receive msg.
2.add the countDownLatch.await() the apps can get the msg






18234105447@163.com
 
From: Jon Chambers
Date: 2020-09-10 08:18
To: jchambers/pushy
CC: huangjunchao; Mention
Subject: Re: [jchambers/pushy] send will not fire when targeting a single user, unless explicitly call Fulture.get() . Under version 0.14.1 (#802)
@huangjunchao I've copied/pasted your example into a unit test in the test-802 branch and the test passes. I am still unable to reproduce the problem.
What I need from you (or anybody else in this thread) at this point is either:
A unit test that I can run that demonstrates this problem or
A complete, executable Java application that demonstrates this problem. The examples provided aren't enough; if you want to take this approach, I need a complete (but minimal!) application that compiles and runs. If it doesn't have public static void main, it's not a complete example.
Thank you for your help in getting to the bottom of the problem.

**Comment by jchambers** [comment]
Ah—I see what's happening here. This is most definitely not a bug and is, I think, what I [originally suspected](https://github.com/jchambers/pushy/issues/802#issuecomment-678795522).

The problem is that you're starting a process that will complete some time in the future—sending a push notification and getting the reply—but are shutting down the JVM before that process has time to complete. You _must_ somehow wait for the operation to complete if you want to receive the reply from the APNs server; the JVM will not do that for you.

When you send many notifications, the process of sending those notifications takes long enough that some (but I'm guessing not _all_) of the replies have time to come back. It may also be that you're sending lots of notifications from some context where the JVM keeps running for a long time, like in a web application.

Here's a very simple example:

```java
public static void main(final String... args) {
    CompletableFuture.runAsync(() -> {
        System.out.println("Sleeping for 8 seconds");

        try {
            Thread.sleep(8_000);
        } catch (InterruptedException e) {
            System.err.println("Interrupted while sleeping");
        }

        System.out.println("Done sleeping!");
    });
}
```

This example will exit immediately without doing much of anything. It _might_ print "Sleeping for 8 seconds," but in almost all cases it will just exit without even doing that much. The problem is that we've started a process that will take a long time (8 seconds) to complete, but aren't waiting for it to finish.

As an analogy, putting a letter in a mailbox is very quick, but it will still take a relatively long time for the letter to arrive at its destination and for a reply to come back. In this example, we're putting the letter in the mailbox, then immediately giving up because we haven't received a reply.

The same is true with Pushy; calling `sendNotification` is like putting a letter in the mail. Calling `sendNotification` is very quick, but if you want the reply, you must wait for it somehow.

I hope that helps!

**Comment by liuxu0703** [comment]
Sorry for this late reply, been a little too busy about other things...
In our case, the demo was started in a web server application, which will not quit until we shut it down. That is why we can receive the first reply when a second push was fired.
Like the good author said, it is a little tricky to provide the demo since many private configurations and keys are involved. We will keep an eye on the issue, and if we can find a pattern, I will write the reproduce steps here.
Thanks again for this marvelous lib and many thanks for your time spend on this issue.
