### ISSUE TITLE
Identify the apnsID and the status error code from header response obtained from APNS when failed to deliver a push

### ISSUE THREAD

**Issue by Sharooque123** [jchambers/pushy#805]
As mentioned in the Apple site [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/handling_notification_responses_from_apns), is it possible to interpret header response from APNS  in the Pushy library?

**Comment by jchambers** [comment]
Yes. Please see [`PushNotificationResponse`](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/PushNotificationResponse.html). Handling responses is [explained in detail in the README](https://github.com/jchambers/pushy#sending-push-notifications).
