### ISSUE TITLE
General OpenSslEngine problem

### ISSUE THREAD

**Issue by liyufu** [jchambers/pushy#812]
We use jdk1.8，when we invoke the method
`final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =sendNotificationFuture.get();`
，We are got a error exception ，like this，follow is the exception message.

![image](https://user-images.githubusercontent.com/7289027/93989220-369a9200-fdbc-11ea-8574-b0ef2ed34097.png)

**Comment by liyufu** [comment]
I have resolved it by update jdk8.0 to the Latest version,it supported the TLSV1.3。
or you can update to the jdk 11

![Uploading image.png…]()

**Comment by jchambers** [comment]
Okay. Sounds like this is resolved, and so I'll close the issue.
