### ISSUE TITLE
PushNotificationFuture await() hangs forever

### ISSUE THREAD

**Issue by QILI92** [jchambers/pushy#814]
Hi @jchambers ,

Not sure this is related to #742 or not, but await() of **PushNotificationFuture** may hang forever after running for a while in production. All following calls to the affected ApnsClient will hang at await() as well.
```
Future<PushNotificationResponse<ApnsPushNotification>> pushNotificationResponseFuture = apnsClient.sendNotification(notification);

pushNotificationResponseFuture.await(); // this triggers
```
Our environment: pushy: **0.13.7**, jdk: 1.8

Thanks!

**Comment by jchambers** [comment]
I'm afraid this isn't enough information to do meaningful debugging. As you might imagine, we have unit tests that cover this basic case, and they do indeed pass.

Is there anything in your logs that can help us understand what's happening?

**Comment by QILI92** [comment]
Hi @jchambers,

Nice to talk back with you. We don't see any ERROR/WARN or meaningful logs, but we indeed don't print logs in the metric listeners if that matters. Secondly, the issue happens after running more than several months in our production, our traffic may have increased to cause the issue. 

What I just do to quickly fix is:
1. Upgrade to 0.14.1
2. Change from blocking to non-blocking sending (no future.get() or future.await() anymore)
3. Add logs in metric listeners

We are looking forward to your advices on a good fix solution.

BTW, one of our concerns is any difference on the payload building with a major version change from 0.13.7 to 0.14.1, for example, we see `payloadBuilder.buildWithDefaultMaximumLength());` is gone from the sdk.

Thanks!

**Comment by fuzan** [comment]
hi @jchambers ,  i am in same team with @QILI92 .
and i can provide some more details:
```java
return new ApnsClientBuilder()
                .setApnsServer(endpoint)
                .setSigningKey(signingKey)
                .setConnectionTimeout(Duration.ofSeconds(30))
                .setMetricsListener(new MessageApnsClientMetricsListener())
                .build();
```
this is our code for APN client, and when we are calling 
```java
public <T extends ApnsPushNotification> PushNotificationFuture<T, PushNotificationResponse<T>> sendNotification(final T notification) 
``` method, especially for a period ( 1 hour is very common ), our APN client will become stale, not able to send any notifications anymore.
So can I ask some questions:
because our APN client is not a concurrent model ( we are using default concurrent value 1 ), Can one channel issue( blocked/long time hanging) cause then entire APN client hang?
And ```java
this.channelPool.acquire()
``` is there a way to identify this lock states? thanks in advance.

**Comment by jchambers** [comment]
It sounds like you might be affected by the same issue described in this mailing list thread: https://groups.google.com/g/pushy-apns/c/adcJ6ZjupYw/m/Yp3B95bRBgAJ

If you have an opportunity to capture some frame logs (see [`ApnsClientBuilder#setFrameLogger(...)`](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/ApnsClientBuilder.html#setFrameLogger(io.netty.handler.codec.http2.Http2FrameLogger)), that would be an enormous help in figuring out what's going on here.

**Comment by petrdvorak** [comment]
@jchambers We are seeing a very similar issue. Apologies for the lack of knowledge in this but could you please elaborate a bit more on how to use the frame logger, i.e. how to plug it together with our SL4J logging?

**Comment by jchambers** [comment]
@petrdvorak Would you mind moving this part of the discussion to the mailing list? I'm happy to help, but that seems to be where most of the debugging conversation is happening right now, and I think that's probably the best place to share knowledge about logging.

Thanks!

**Comment by jchambers** [comment]
Folks, we have a number of running discussions about this issue. To keep things focused, I'm going to close this issue and try to consolidate discussion in #816. Please let me be clear that there's more work to be done, but I think it'll be easiest to have all of the information in one place. Let's continue the discussion in the new ticket.

Thanks!
