### ISSUE TITLE
About Invalid Devices when using the http2!

### ISSUE THREAD

**Issue by leiwei999** [jchambers/pushy#823]
I had to take into account that there are no invalid devices when using the http1.1, and I don't think http2 needs any special consideration. Am I understanding you correctly?

The following is information from the developer website.
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH13-SW1

If you send a notification that is accepted by APNs, nothing is returned.

If you send a notification that is malformed or otherwise unintelligible, APNs returns an error-response packet and closes the connection. Any notifications that you sent after the malformed notification using the same connection are discarded, and must be resent. Figure A-2 shows the format of the error-response packet.

Best regards.

**Comment by jchambers** [comment]
The document you linked is for an outdated version of the APNs protocol. I'm not entirely sure if I understand your question, but the result of sending a notification—whether successful or not—will always be reported by the `Future` returned when you send a notification.
