### ISSUE TITLE
Does pushy close high latency connections and open new ones?

### ISSUE THREAD

**Issue by ben512** [jchambers/pushy#827]
Per [Best Practices While Connecting to APNs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/)

Sender should "Depending on throughput and request-response turnaround time, open new connections."

Just wondering does pushy supports this?

Thanks!

**Comment by jchambers** [comment]
No; to be frank, it's not clear to me what that suggestion means in practice. I'm going to close this for now because it's not clear what implementing this suggestion would even. I'd be happy to open feature request tickets for more specific requests supported by concrete use cases, though!
