### ISSUE TITLE
How To Send Notification when having different certificates?

### ISSUE THREAD

**Issue by hxdwd** [jchambers/pushy#828]
Hello
      I got a question when using Pushy to send notification to APNs. 
      I wanna to send by different certificates which are different cuz IOS certificates are different since 13.
      but when creating ApnsClient need to determine p12File and p12Password.
      I wanna konw its there any channces that creating ApnsClient can use different certificates.
      THANK!

**Comment by jchambers** [comment]
I'm not entirely sure if I understand the question, but I think you might be asking for the same thing that's described in #540. If so, the current solution is to have multiple `ApnsClient` instances. I hope to have multi-credential clients in play soon.

**Comment by jchambers** [comment]
Oops. Published that comment before I meant to. If I've misunderstood and that does NOT answer your question, please post a follow-up comment here and we'll reassess.

**Comment by hxdwd** [comment]
Thanks for reply. Sorry for the poor expressing.
In my case, I need to have multiple ApnsClient instances to send notifications. It's kinda duplicate.
Anyway, Thanks.

**Comment by jchambers** [comment]
Understood. Definitely hoping to improve the duplication situation soon. I recommend subscribing to #540 for updates!
