### ISSUE TITLE
Confused when using ConcurrentConnections and EventLoopGroup

### ISSUE THREAD

**Issue by hxdwd** [jchambers/pushy#830]
Hello.
    I got a question when using EventLoopGroup  and ConcurrentConnections parameters to create ApnsClient instance.
    Oh, The Version is 0.13.9.
    When the two parameters are 6 - 2, I sent  about 2000 msgs at one time. I used jvisualvm tools to check the result.
    You can see about 300threads was created. It's too many!
![image](https://user-images.githubusercontent.com/52123579/98343173-67711680-204c-11eb-8b7e-cc025df072ad.png)

![image](https://user-images.githubusercontent.com/52123579/98344177-d56a0d80-204d-11eb-817c-8fc5e17f32b0.png)
    Also, When I checked the thread at logs file, It seemed just about 6 threads was working.  Where is the rest of created threads?
![image](https://user-images.githubusercontent.com/52123579/98343557-f4b46b00-204c-11eb-8ea1-115fe116d3c7.png)

**Comment by hxdwd** [comment]
the code is like this.
![image](https://user-images.githubusercontent.com/52123579/98344695-94bec400-204e-11eb-850d-3d82bce21036.png)

**Comment by jchambers** [comment]
It's hard to tell what's happening here without more information. If you're creating a single `NioEventLoopGroup` with 4 threads as shown in your example, then there should be just 4 `nioEventLoopGroup` threads. Do you have multiple `ApnsClient` instances? Are you creating a new event loop group for each?

**Comment by hxdwd** [comment]
Thanks for the reply.
I do creating a new event loop group each time creating multiple ApnsClient instances. That's why there are too many threads created.
After changing the code, It works fine.
![image](https://user-images.githubusercontent.com/52123579/98519546-df894780-22ab-11eb-93cb-cb4f1db74a4c.png)

**Comment by jchambers** [comment]
Great! Shall we consider this issue resolved, then?
