### ISSUE TITLE
Batch send APNs

### ISSUE THREAD

**Issue by damangueyu** [jchambers/pushy#832]
Is there a method to send in bulk?

**Comment by jchambers** [comment]
No, and we don't plan to add one.

There's no protocol-level affordance for sending messages in bulk; other than syntactic sugar, Pushy couldn't really offer any advantage over a `for` loop. Even then, we'd have to make assumptions about flow control and error handling that couldn't possibly be right for all use cases.

**Comment by jchambers** [comment]
Thank you for the suggestion, of course!
