### ISSUE TITLE
Provide automatic module name to avoid clash with old com.turo packages

### ISSUE THREAD

**Issue by piotrblasiak** [jchambers/pushy#838]
I experience a problem due to the old com.turo package and the new one having the same artifactId which becomes the automatic module name in java modules (JPMS), and such in a module project with both only one of them will be available to the compiler. Exactly this happens when you use jpasskit, which uses the old pushy:

https://github.com/drallgood/jpasskit/issues/304

Also see: http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by jchambers** [comment]
I took a shot at this in #906. Feedback is very welcome!
