### ISSUE TITLE
Use token to verify push, always return invalidprovidertoken

### ISSUE THREAD

**Issue by xiaolanbuzaiaixinyi** [jchambers/pushy#839]
import maven :<dependency>
            <groupId>com.eatthepath</groupId>
            <artifactId>pushy</artifactId>
            <version>0.14.2</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.34.Final</version>
            <scope>runtime</scope>
        </dependency>

Test source code ：
@Component
public class AnpsClientUtil {

    private static final Logger logger = LoggerFactory.getLogger(AnpsClientUtil.class);

    private static String teamId = "NK37SPV8GQ";
    private static String keyId = "H4BC8WC6XY";
    private static String p8File = "/Users/longskr/dataSource/AuthKey_H4BC8WC6XY.p8";
    private static String topic = "com.winat.recording.ad";
    private static final Semaphore semaphore = new Semaphore(10000);
    private static ApnsClient apnsClient = null;

    public static void main(String[] args) {
        AnpsClientUtil.push(Collections.singletonList("abd1d8844bac9db0850d0f4405e252adff961c9d15a4167e9a2a71ea65019b75"),
                "title","boday",true,null, 0);
    }

    public static ApnsClient getAPNSConnect() {

        if (apnsClient == null) {
            try {
                //证书
                EventLoopGroup eventLoopGroup = new NioEventLoopGroup(4);
                apnsClient = new ApnsClientBuilder().setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                        .setSigningKey(ApnsSigningKey.loadFromPkcs8File(new File(p8File),
                                teamId,keyId ))
                        .setConcurrentConnections(4).setEventLoopGroup(eventLoopGroup).build();

            } catch (Exception e) {
                logger.error("ios get pushy apns client failed!");
                e.printStackTrace();
            }
        }
        return apnsClient;
    }

    /**
     * ios的推送
     * @param deviceTokens
     * @param alertTitle
     * @param alertBody
     * @param contentAvailable
     * @param customProperty
     * @param badge
     */
    @SuppressWarnings("rawtypes")
    public static void push(final List<String> deviceTokens, String alertTitle, String alertBody, boolean contentAvailable, Map<String, Object> customProperty, int badge) {
        long startTime = System.currentTimeMillis();
        ApnsClient apnsClient = AnpsClientUtil222.getAPNSConnect();
        long total = deviceTokens.size();
        //每次完成一个任务（不一定需要线程走完），latch减1，直到所有的任务都完成，就可以执行下一阶段任务，可提高性能
        final CountDownLatch latch = new CountDownLatch(deviceTokens.size());
        //线程安全的计数器
        final AtomicLong successCnt = new AtomicLong(0);
        long startPushTime = System.currentTimeMillis();
        for (String deviceToken : deviceTokens) {
            ApnsPayloadBuilder payloadBuilder = new ApnsPayloadBuilder();
            if (alertBody != null && alertTitle != null) {
                payloadBuilder.setAlertBody(alertBody);
                payloadBuilder.setAlertTitle(alertTitle);
            }
            //如果badge小于0，则不推送这个右上角的角标，主要用于消息盒子新增或者已读时，更新此状态
            if (badge > 0) {
                payloadBuilder.setBadgeNumber(badge);
            }

            //将所有的附加参数全部放进去
            if (customProperty != null) {
                for (Map.Entry<String, Object> map : customProperty.entrySet()) {
                    payloadBuilder.addCustomProperty(map.getKey(), map.getValue());
                }
            }
            // true：表示的是产品发布推送服务 false：表示的是产品测试推送服务
            payloadBuilder.setContentAvailable(contentAvailable);
            String payload = payloadBuilder.buildWithDefaultMaximumLength();
            final String token = TokenUtil.sanitizeTokenString(deviceToken);
            SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(token, topic, payload);
            try {
                //从信号量中获取一个允许机会
                semaphore.acquire();
            } catch (Exception e) {
                //线程太多了，没有多余的信号量可以获取了
                logger.error("ios push get semaphore failed, deviceToken:{}", deviceToken);
                e.printStackTrace();
            }

            final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient.sendNotification(pushNotification);

            //---------------------------------------------------------------------------------------------------
            try {
                final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse = sendNotificationFuture.get();
//                System.out.println(sendNotificationFuture.isSuccess());
//                System.out.println(pushNotificationResponse.isAccepted());

                sendNotificationFuture.addListener(new PushNotificationResponseListener<SimpleApnsPushNotification>() {

                    @Override
                    public void operationComplete(final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> future) throws Exception {
                        // When using a listener, callers should check for a failure to send a
                        // notification by checking whether the future itself was successful
                        // since an exception will not be thrown.
                        if (future.isSuccess()) {
                            final PushNotificationResponse<SimpleApnsPushNotification> pushNotificationResponse =
                                    sendNotificationFuture.getNow();
                            if (pushNotificationResponse.isAccepted()) {
                                successCnt.incrementAndGet();
                            } else {
                                Date invalidTime = pushNotificationResponse.getTokenInvalidationTimestamp();
                                logger.error("Notification rejected by the APNs gateway: " + pushNotificationResponse.getRejectionReason());
                                if (invalidTime != null) {
                                    logger.error("\t…and the token is invalid as of " + pushNotificationResponse.getTokenInvalidationTimestamp());
                                }
                            }
                            // Handle the push notification response as before from here.
                        } else {
                            // Something went wrong when trying to send the notification to the
                            // APNs gateway. We can find the exception that caused the failure
                            // by getting future.cause().
                            future.cause().printStackTrace();
                        }
                        latch.countDown();
                        semaphore.release();//释放允许，将占有的信号量归还
                    }
                });
                //------------------------------------------------------------------

                if (pushNotificationResponse.isAccepted()) {
                } else {
                    logger.error("Notification rejected by the APNs gateway: " + pushNotificationResponse.getRejectionReason());

                    if (pushNotificationResponse.getTokenInvalidationTimestamp() != null) {
                        logger.error("\t…and the token is invalid as of " + pushNotificationResponse.getTokenInvalidationTimestamp());
                    }
                }
            } catch (final ExecutionException e) {
                logger.error(e.getMessage(), e);
            } catch (InterruptedException e) {
                logger.error(e.getMessage(), e);
            }
            //---------------------------------------------------------------------------------------------------

        }

        try {
            latch.await(20, TimeUnit.SECONDS);
        } catch (Exception e) {
            logger.error("ios push latch await failed!");
            e.printStackTrace();
        }

        long endPushTime = System.currentTimeMillis();

    }

**Comment by jchambers** [comment]
It looks like you've resolved this issue on your own, but for the benefit of future readers, can you explain what was wrong and how you solved the problem?
