### ISSUE TITLE
How To Access Actual APNS Response?

### ISSUE THREAD

**Issue by MrThreepwood** [jchambers/pushy#840]
I've currently got an issue in that there doesn't appear to be a good way to programmatically decide whether or not to retry a request. While readme claims that if an exception isn't thrown, the notification should not be retried, that doesn't seem accurate.

If apple responds with a 500, that doesn't imply that the issue is on my end.

If I have a bad configuration that results in a 403, then I need to fix the configuration and try again, but I need to know whether the notification itself is bad (as in the user is no longer registered). For any other reason really, I need to hang on to that notification in my DB/Message Bus and try again once I've fixed the configuration.

Right now the only thing I can see that I can access is the rejection reason (which is a string), and I'm not entirely sure how well formatted that is going to be and don't know if there's anything reasonable to compare it to.

**Comment by MrThreepwood** [comment]
I had a quick look at the code, and it looks like providing the status in the SimplePushNotificationResponse would be very easy. I'd be happy to submit a pull request if that's something that would be accepted.

**Comment by jchambers** [comment]
I took a shot at this in #890. Feedback is welcome!

**Comment by jchambers** [comment]
I've merged #390, and this will be in the next Pushy release.
