### ISSUE TITLE
How do we go about including the GeoTrust and AAACertificateServices certificates required by Apple?

### ISSUE THREAD

**Issue by robertmanea** [jchambers/pushy#845]
My push notifications have stopped working on my Spring app. I've recently included these in a PHP app  that's using edamov/pushok in order to interact with APNS, but I have no idea how to do this with pushy.

**Comment by robertmanea** [comment]
I'm now receiving "Received GOAWAY from APNs server: {"reason":"Shutdown"}"... Don't know if it's related, but I'm guessing it is

**Comment by jchambers** [comment]
Folks, please see #809 and #810 for additional discussion on this issue. The summary is that we do not expect that users will need to do anything to be ready for the change to AAACertificateServices.

I'll close this issue as a duplicate for now, but (as always) please let me know if you feel that's a mistake.

**Comment by jchambers** [comment]
> I'm now receiving "Received GOAWAY from APNs server: {"reason":"Shutdown"}"... Don't know if it's related, but I'm guessing it is

And no, this is in no way related. Please see Apple's documentation for an explanation of the various "reason" values. "Shutdown" means that the specific server you were talking to was shut down for maintenance and you should just retry sending the notification.

**Comment by jchambers** [comment]
> there shouldn't be any issue when Geotrust is dropped, provided people also remember to setup http2.

I'm not quite sure if I understand what you mean by "setup HTTP/2," but I think you're referring to Apple shutting down the old binary protocol in the near future. Pushy has been using HTTP/2 exclusively for years, and there shouldn't be any action required for Pushy users there, either.

**Comment by dzianismaroz** [comment]
Sorry for bothering. But I'm trying to understand: are any actions required on 31 March about AAACertificate ?
In case of using pushy by jdk8 on Debian 7/ Debian 10 :  it will still work ok after 31 March? Should i perform any actions by adding AAACertificate to target environment in any way ?
Thanks
