### ISSUE TITLE
How to set TLS protocol to use "TLSv1.2"?

### ISSUE THREAD

**Issue by mikezang** [jchambers/pushy#861]
Can you provide setTLSProtocols method?
Our server use TLSv1 as default TLS protocols, so we can't push notification to Apple, we can push notification after append code `.protocols("TLSv1.2")` in `ApnsClientBuilder.java` as below:

> final SslContextBuilder sslContextBuilder = SslContextBuilder.forClient()
　.protocols("TLSv1.2")
　.sslProvider(sslProvider)
　.ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE);`

**Comment by jchambers** [comment]
I'm not sure if I understand the question. When Pushy connects to the server, it should announce all of the TLS versions it supports, and the server should then choose an appropriate one from the list. If the server wants TLSv1.2 and your client supports TLSv1.2, then the session should use TLSv1.2. There should be no need to explicitly set the version.

Can you please say more about why you think you need to set the version explicitly? What specifically is going wrong?

**Comment by mikezang** [comment]
Some companies server might not set to allow all TLS version, in that case you project won't request to Internet.
If you can provide method to set which TLS version as default, that will let Pushy is more easy to be used.
In SSLContext class, we can select SSL version like `SSLContext sslContext = SSLContext.getInstance("TLSv1.2")`...

**Comment by jchambers** [comment]
I'm still not sure if I understand this situation. In a TLS "hello" message, a client sends the server the _highest_ version of TLS it supports, and then the server chooses a version at or below the level the client supports.

To my knowledge—and this may be where I'm misunderstanding you—there isn't a way to have the JVM support a version of TLS without advertising it in a TLS "hello." If your JVM isn't automatically negotiating to TLSv1.2 or newer, I think that means that the JVM simply doesn't support that version of TLS, and providing a way to request that version in `ApnsClientBuilder` won't make much of a difference.

For context, I'm looking at the "Changing default TLS protocol version for client end points : TLS 1.0 to TLS 1.2" section of ["Additional information on Oracle's JDK and JRE Cryptographic Algorithms"](https://java.com/en/configure_crypto.html), which says in part (with emphasis added):

> For example, if the value of [`jdk.tls.client.protocols`] is "TLSv1.1,TLSv1.2", then the default protocol settings on the client for TLSv1.1 and TLSv1.2 are enabled on the client, _while SSLv3, TLSv1, and SSLv2Hello are disabled on the client.)

Am I misunderstanding your situation? If so, can you explain how your JVM is configured such that it won't advertise a TLS version it really does support or, alternatively, point me to the documentation explaining your situation?

**Comment by kaioufcg** [comment]
We want to be able to configure the SSL PROTOCOL version in JDK and OpenSSL SslContext.
We need this because we need to be able to limit the SSL protocol to TLSv1.2, however, this does not seem to be possible currently.

We can optionally have a separate mapping for specifying SSL protocol with a uniform interface for both Jdk and OpenSsl.

Please let me know if you can think of a better way of making the SSL protocol configurable in the SslContexts.

**Comment by jchambers** [comment]
> we need to be able to limit the SSL protocol to TLSv1.2

When you say "limit," do you mean you're trying to set a _minimum_ version or a _maximum_ version? What situation are you trying to avoid?

**Comment by jchambers** [comment]
Folks, I don't mean to be difficult, but I do need more information to meaningfully act on this request.

@mikezang all of the open questions stand, but backing waaaaaay up to the initial question, you wrote:

> …we can't push notification to Apple, we can push notification after append code `.protocols("TLSv1.2")` in `ApnsClientBuilder.java`…

Can you please be more specific about what went wrong? Can you share a stack trace or error message or anything along those lines?

**Comment by kaioufcg** [comment]
> > precisamos ser capazes de limitar o protocolo SSL ao TLSv1.2
> 
> Quando você diz "limite", quer dizer que está tentando definir uma versão _mínima_ ou uma versão _máxima?_ Que situação está tentando evitar?

Hi, I want to thank you for your attention. I don't know if I'm sure about this, but I would like to be able to set a minimum version of use, in my case, I can't use version lower than TLSv1.2 for security reasons.

**Comment by jchambers** [comment]
Reading this again, I think the request is to address an unusual and narrow use case where:

- Pushy is running in a JVM that technically supports TLSv1.2 or 1.3
- Even though the JVM supports those protocols, they have been turned off by default via `jdk.tls.client.protocols` for some reason
- The purpose of the requested configuration option is to override the global defaults

If that's the case, I think I at least understand the request, but it sounds so unusual that I'm having a hard time imagining this being a widespread need. @mikezang am I understanding the situation correctly? @kaioufcg does this accurately summarize your situation, too?

If so, can you please explain why you can't turn on TLSv1.2 or 1.3 globally?

**Comment by jchambers** [comment]
Folks, given the information available, I don't currently intend to make changes to how we're handling TLS versions, and so will close this ticket for now. If you have additional information to share, please leave a comment here and I'll happily revisit the issue!
