### ISSUE TITLE
Manifest issues

### ISSUE THREAD

**Issue by MushyMiddle** [jchambers/pushy#862]
Hi.  I'm working on integrating pushy to replace javapns for HTTPS/2 support.  Our app runs in an OSGi environment, so the manifest is critical for us.  Two problems I've seen so far:

* fast-uuid-0.1.jar does not have an OSGi manifest, so cannot be imported from pushy-0.14.2.jar.  In its current form, it would need to be included as a private library, and removed from the manifest.
* pushy-0.14.2.jar's manifest both exports and imports the same packages.  This causes the bundle to not load - it should only (need to) export those packages.

Manually editing pushy-0.14.2.jar's manifest to remove those imports, and adding a proper manifest to fast-uuid-0.1.jar allows the bundles to load OK.

Here's the manifest I added/edited for fast-uuid (mostly copied from pushy-0.14.2.jar's):

`Manifest-Version: 1.0`
`Built-By: jon`
`Created-By: Apache Maven 3.3.9`
`Bundle-Description: A Java library for fast UUID stuff`
`Bundle-License: http://opensource.org/licenses/MIT`
`Bundle-SymbolicName: com.eatthepath.uuid`
`Built-By: jon`
`Bnd-LastModified: 1603298218405`
`Bundle-ManifestVersion: 2`
`Bundle-DocURL: https://github.com/jchambers`
`Bundle-Vendor: Jon Chambers`
`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"`
`Tool: Bnd-4.2.0.201903051501`
`Export-Package: com.eatthepath.uuid`
`Bundle-Name: Fast UUID`
`Bundle-Version: 0.1`
`Build-Jdk: 14.0.1`

**Comment by jchambers** [comment]
Thanks for the report. I'll get to this when I can, but there are few higher-priority issues I need to address first. In the meantime, I invite you to open a pull request!

**Comment by jchambers** [comment]
With apologies for the delay and thanks for the contributions, this should be resolved in #905.
