### ISSUE TITLE
ApnsClientBuilder set preferred SSL provider

### ISSUE THREAD

**Issue by jolheiser** [jchambers/pushy#877]
I see that at one point there was the option to set your own preferred SSL Provider, however it was removed in https://github.com/jchambers/pushy/pull/440.

Was it intentional to remove it, e.g. is there a way to achieve this same effect that is simply in a spot I haven't discovered?

**Comment by jchambers** [comment]
Can you please say more about your use case so I can offer a more informed answer to your question?

**Comment by jolheiser** [comment]
Trying to run on WebSphere using the WAS socket factory instead of JDK.

**Comment by jolheiser** [comment]
We have gone with a different solution.

I know that this issue was moreso the fault of our WAS setup and not this library in particular, so I will close it. Thank you for your work on the library! :slightly_smiling_face:

**Comment by jchambers** [comment]
I'm glad you got it resolved, and I'm also sorry I didn't get back to you sooner!
