### ISSUE TITLE
Api docs link broken

### ISSUE THREAD

**Issue by Ditscheridou** [jchambers/pushy#901]
Hi guys,

i wanted to dive into pushy, but the link for the [Api docs](https://github.com/jchambers/pushy/wiki/API-Documentation) is broken. Can someone point me where you moved to?

**Comment by jchambers** [comment]
The link on the wiki has been fixed and now (correctly) points to https://pushy-apns.org/apidocs/0.14/index.html. Thanks for the heads-up!

FWIW, you can also find the link in the README and on the project page. If you're working from an unreleased branch, you can also generate the docs locally with `mvn javadoc:javadoc`.
