### ISSUE TITLE
Sending notifications stop

### ISSUE THREAD

**Issue by adriansanchez22** [jchambers/pushy#907]
Hi all!
In summary, we use pushy in an application with a daily delivery of 7,200 IOS notifications approx.
Every X days the delivery service stops and is only restored by restarting the application servers. We have tried to add as many traces to the flow but the only thing we can see is that the last trace shown is before this code:

```java
final PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient.sendNotification(pushNotification);
```

Is there any limit on sending notifications by ip?
We dont see any specific error in the application traces to help us, we only currently know that restarting the app restores communications.

Best regards,
Adrián.

**Comment by jchambers** [comment]
No, there's no limit by IP. Many users send literally billions of push notifications per day without trouble. Can you please clarify what you mean by "delivery stops?" Are you still receiving acknowledgements from the APNs server, or are futures never completing?

**Comment by jchambers** [comment]
Depending on what's going on, this _may_ be helped by #913, but it's hard to say for sure without more information.
