### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by mistahenry** [jchambers/pushy#908]
Hi,

This [issue](https://github.com/jchambers/pushy/issues/865) still affects a production instance of mine on occasion. Do you have a plan for when you are going to create the next release for this project?

I'm able to compile and create the release myself if necessary, so this issue is really just my curiosity around:

1. When you will be creating the next release
2. If there's issue's in the current master that I should be aware of such that creating a release now wouldn't be a good idea.

Thanks

**Comment by jchambers** [comment]
Pushy v0.15.0 has been released. Please note that opening this issue had no bearing on the release timing, and we had been steadily moving toward release over the past month.

> I'm able to compile and create the release myself if necessary…

I take that in a helpful spirit, but if by "create the release yourself" you mean "publish to Maven Central," please note that would not be helpful and would, in my view, actually be significantly counterproductive. While I appreciate the desire to help, please do not do that now or in the future.

**Comment by mistahenry** [comment]
@jchambers Awesome! 

> I take that in a helpful spirit, but if by "create the release yourself" you mean "publish to Maven Central," please note that would not be helpful and would, in my view, actually be significantly counterproductive. While I appreciate the desire to help, please do not do that now or in the future.

Sorry if that was unclear by my phrasing. I meant pull down the repo and run whatever gradle/maven steps would be necessary to produce a jar that I could use in my own project via

`implementation(files("libs/custom-compiled-lib-0.14.1-HOTFIX.jar"))`

The spirit of this issue was just to gain a bit more info into a process that's opaque to me as an outsider who's using this as a component in a critical piece of software. Nothing more. 

Anyway, great work :) We've used your library to send hundreds of millions of pushes in the last 6 months. Thanks for all you've done here

**Comment by jchambers** [comment]
Totally understood, and I figured that was the case. Cheers, and thanks for the support and kind words!
