### ISSUE TITLE
Notification rejected by the APNs gateway: Optional[InvalidProviderToken]

### ISSUE THREAD

**Issue by suganyagladys** [jchambers/pushy#914]
Hi, 

I am able to send Push Notification with the same KeyId,TeamId and .p8 file from PN tester. Running the java code for PN i am getting the response as  Notification rejected by the APNs gateway: Optional[InvalidProviderToken]

**Comment by jchambers** [comment]
Respectfully, issues like these get opened from time to time and they invariably get closed with something like "I accidentally switched the key ID and team ID." I'm happy to help, but strongly, strongly suspect this isn't a bug that we can fix with a change to Pushy itself. With that in mind, I'm going to convert this to a discussion.
