### ISSUE TITLE
/json/JsonSerializer: escaping '/' ?

### ISSUE THREAD

**Issue by KKMunich** [jchambers/pushy#918]
Hi guys,
I have the problem that the JSONSerializer escapes slashes.
Certainly I understand escaping of the control characters, but what's so dangerous with a slash?

JsonSerializer.writeJsonValue():
 if (c == '"' || c == '\\' || c == '/' || c == '\b' || c == '\f' || c == '\n' || c == '\r' || c == '\t' || Character.isISOControl(c)) {
                    appendEscapedCharacter(c, out);

I'd recommend to remove '/' from this escaping.

Best regards

**Comment by jchambers** [comment]
The JSON standard calls for '/' characters to be escaped: https://datatracker.ietf.org/doc/html/rfc7159#section-7

Since the current behavior is in keeping with the standard, I'm not inclined to change it. Thanks for your interest, though!

**Comment by KKMunich** [comment]
Oh - I see!
Thanks a lot for the quick and helpful answer - I didn't guess that.
