### ISSUE TITLE
Specifying a custom JWT token

### ISSUE THREAD

**Issue by kevmo314** [jchambers/pushy#932]
How do I specify a custom JWT token instead of having pushy generate it? The documentation is unclear.

**Comment by jchambers** [comment]
Pushy doesn't offer an affordance to provide your own JWT token. I don't think I understand the use case, though; why would you want to do that?

**Comment by kevmo314** [comment]
We have a separate service that handles our token issuance to restrict access to the private key for other use cases. We're okay with the token not auto-refreshing.

**Comment by jchambers** [comment]
I think the answer is "Pushy doesn't support this use case," but I still think there's a good chance I'm (still) misunderstanding what you're trying to do. In particular:

> We're okay with the token not auto-refreshing.

That would mean your connections would stop working every hour unless we also added a way to manually close connections on demand. Is that what you'd intend to do in your use case?

**Comment by jchambers** [comment]
I'm going to close this for now; if you have more thoughts to share, please feel free to leave a comment and we'll happily revisit the issue. Thanks!
