### ISSUE TITLE
Upgrading to 0.15.0 I had trouble with the localhost test SSL certs 

### ISSUE THREAD

**Issue by hikuley** [jchambers/pushy#940]
In my testing upgrading to 0.15.0 I had trouble with the localhost test SSL certs for MockApnsServer

I kept getting: ` java.security.cert.CertificateException: No name matching localhost found`

exceptions that slowed down the Java server to a halt.

**Comment by jchambers** [comment]
This appears to be a duplicate of https://github.com/jchambers/pushy/discussions/936. I'm confident that discussion will give you the answers you need, but if not, please post a comment here and we'll reopen the issue. Thanks!
