### ISSUE TITLE
Specify alert as simple string instead of dictionary

### ISSUE THREAD

**Issue by kelfink** [jchambers/pushy#941]
We're adapting our server side code to use the pushy library (awesome lib, thank you for writing it). We need to maintain the older style still allowed by Apple's docs:  [docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification) where it says it may be "Dictionary (or String)".   Our app basically can't handle the alert being a dictionary at this point.  I see there's a setCustomProperty call but that won't let me get the alert inside the aps key where it is needed.  And if I need to add a sound node, that one ends up inside the aps key while the alert does not.  

Is there a way around this?  thanks

**Comment by kelfink** [comment]
Oh, I just found apnspayloadBuilder.setPreferStringRepresentationForAlerts(true);
which seems to trigger exactly the behavior I was looking for.  the alert body gets put into the alert key as a plain key.

**Comment by jchambers** [comment]
>  I just found apnspayloadBuilder.setPreferStringRepresentationForAlerts(true);
which seems to trigger exactly the behavior I was looking for

Indeed, that should do it! Sounds like your issue is resolved, so I'll go ahead and close this ticket. Cheers, thanks for the kind words, and welcome to the community!
