### ISSUE TITLE
Add request timeout

### ISSUE THREAD

**Issue by pertu** [jchambers/pushy#945]
The problem: in case of network failures some requests get stuck until the APNS connection restores.  

Steps to reproduce:
1. Make multiple (1000 or so) simultaneous (push) requests.
2. Break APNS connectivity (or shut down emulator).
3. Wait for a couple of minutes.
4. Restore network (or start emulator).

At step (2) some futures complete with exception, but some get stuck until the (4) step.  
With restored network those "stuck" futures complete as usual.  

I guess throwing something like `TimeoutException` would be a more predicable/reliable behaviour.  
Another option is `apnsClient.send(...).orTimeout(...)`, but it may lead to resource leaks and it doesn't actually cancel the request.  

Maybe related: #433 and #444 (drops write timeout).

What do you think about it?

**Comment by jchambers** [comment]
As you point out:

> …[timing out requests] may lead to resource leaks and it doesn't actually cancel the request.

Pushy has no magic to offer here, and has the same challenges with timing out/cancelling requests as an external caller. And, as you correctly point out, we have attempted this in the past (#433 and #444), and found that timeouts cause more confusion than they resolve.

Given our past experience with a virtually identical feature, I don't think it makes sense to (re-)add this feature, though I certainly understand what you're hoping for!
